/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';

export default function Beachside(props) {
  const { nodes, materials } = useGLTF('/Environment/Beachside.glb');

  return (
    <RigidBody type="fixed" colliders="trimesh" friction={5}>
      <group {...props} dispose={null}>
        <group scale={0.614}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box001_1.geometry}
            material={materials['01___Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box001_1_1.geometry}
            material={materials['02___Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box001_1_2.geometry}
            material={materials['09___Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box001_1_3.geometry}
            material={materials['08___Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box001_1_4.geometry}
            material={materials['04___Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box001_1_5.geometry}
            material={materials['10___Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box001_1_6.geometry}
            material={materials['03___Default']}
          />
        </group>
        <group position={[32.286, 22.11, 56.468]} scale={-7.916}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh1945116984.geometry}
            material={materials.mat21}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh1945116984_1.geometry}
            material={materials.mat12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh1945116984_2.geometry}
            material={materials.mat8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh1945116984_3.geometry}
            material={materials.mat5}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Sand.001']}
          position={[0, 19.486, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials['Sand.001']}
          position={[0, 19.486, 0]}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload('/Environment/Beachside.glb');
