/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Grass(props) {
  const { nodes, materials } = useGLTF('/Environment/Grass.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        name="grass_1"
        geometry={nodes.grass_1.geometry}
        material={materials.mat9}
      />
      <mesh
        name="grass_2"
        geometry={nodes.grass_2.geometry}
        material={materials.mat10}
      />
    </group>
  );
}

useGLTF.preload('/Environment/Grass.glb');
