/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';

export default function Island(props) {
  const { nodes, materials } = useGLTF('/Environment/Island.glb');
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="hull" friction={5}>
        <group
          name="Dock_Wide"
          position={[0, 6.257, 0]}
          rotation={[-Math.PI / 2, 0, -1.573]}
          scale={100}
        >
          <mesh
            name="Dock_Wide002"
            castShadow
            receiveShadow
            geometry={nodes.Dock_Wide002.geometry}
            material={materials['Wood.002']}
          />
          <mesh
            name="Dock_Wide002_1"
            castShadow
            receiveShadow
            geometry={nodes.Dock_Wide002_1.geometry}
            material={materials['LightWood.002']}
          />
        </group>
      </RigidBody>
      <RigidBody type="fixed" friction={5}>
        <group name="OLand" position={[5.804, -26.996, 0]}>
          <mesh
            name="Oland"
            castShadow
            receiveShadow
            geometry={nodes.Oland.geometry}
            material={materials['Dirt.001']}
          />
          <mesh
            name="Oland_1"
            castShadow
            receiveShadow
            geometry={nodes.Oland_1.geometry}
            material={materials['Grass.001']}
          />
        </group>
        <group
          name="Xland"
          position={[122.892, -26.996, 0]}
          rotation={[0, -0.003, 0]}
        >
          <mesh
            name="Xland_1"
            castShadow
            receiveShadow
            geometry={nodes.Xland_1.geometry}
            material={materials['Dirt.001']}
          />
          <mesh
            name="Xland_2"
            castShadow
            receiveShadow
            geometry={nodes.Xland_2.geometry}
            material={materials['Grass.001']}
          />
        </group>
      </RigidBody>
    </group>
  );
}

useGLTF.preload('/Environment/Island.glb');
