/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';

export default function Island(props) {
  const { nodes, materials } = useGLTF('/Environment/Island.glb');
  return (
    <RigidBody type="fixed" colliders="trimesh" friction={5}>
      <group {...props} dispose={null}>
        <group name="Oland" position={[-0.226, -7.566, 0.948]} scale={4.404}>
          <mesh
            name="Cylinder-Mesh"
            castShadow
            receiveShadow
            geometry={nodes['Cylinder-Mesh'].geometry}
            material={materials.Dirt}
          />
          <mesh
            name="Cylinder-Mesh_1"
            castShadow
            receiveShadow
            geometry={nodes['Cylinder-Mesh_1'].geometry}
            material={materials.Grass}
          />
        </group>
        <group
          name="Xland"
          position={[-0.145, -7.566, 0.948]}
          rotation={[-Math.PI, 0.009, -Math.PI]}
          scale={4.404}
        >
          <mesh
            name="Cylinder-Mesh"
            castShadow
            receiveShadow
            geometry={nodes['Cylinder-Mesh'].geometry}
            material={materials.Dirt}
          />
          <mesh
            name="Cylinder-Mesh_1"
            castShadow
            receiveShadow
            geometry={nodes['Cylinder-Mesh_1'].geometry}
            material={materials.Grass}
          />
        </group>
        <group
          name="Dock"
          position={[-0.226, -7.566, 0.948]}
          rotation={[Math.PI, -1.569, Math.PI]}
          scale={4.404}
        >
          <group name="Dock_Wide" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              name="Dock_Wide_1"
              castShadow
              receiveShadow
              geometry={nodes.Dock_Wide_1.geometry}
              material={materials.Wood}
            />
            <mesh
              name="Dock_Wide_2"
              castShadow
              receiveShadow
              geometry={nodes.Dock_Wide_2.geometry}
              material={materials.LightWood}
            />
            <mesh
              name="Dock_Wide_3"
              castShadow
              receiveShadow
              geometry={nodes.Dock_Wide_3.geometry}
              material={materials.String}
            />
          </group>
        </group>
        <group
          name="FlatingIsland1"
          position={[-0.226, 137.334, 0.948]}
          scale={4.404}
        >
          <mesh
            name="Node-Mesh"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh'].geometry}
            material={materials.mat22}
          />
          <mesh
            name="Node-Mesh_1"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_1'].geometry}
            material={materials.mat10}
          />
          <mesh
            name="Node-Mesh_2"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_2'].geometry}
            material={materials.mat9}
          />
          <mesh
            name="Node-Mesh_3"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_3'].geometry}
            material={materials.mat18}
          />
          <mesh
            name="Node-Mesh_4"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_4'].geometry}
            material={materials.mat21}
          />
          <mesh
            name="Node-Mesh_5"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_5'].geometry}
            material={materials.mat6}
          />
          <mesh
            name="Node-Mesh_6"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_6'].geometry}
            material={materials.mat4}
          />
          <mesh
            name="Node-Mesh_7"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_7'].geometry}
            material={materials.mat8}
          />
          <mesh
            name="Node-Mesh_8"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_8'].geometry}
            material={materials.mat13}
          />
          <mesh
            name="Node-Mesh_9"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_9'].geometry}
            material={materials.mat12}
          />
          <mesh
            name="Node-Mesh_10"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_10'].geometry}
            material={materials.mat0}
          />
          <mesh
            name="Node-Mesh_11"
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh_11'].geometry}
            material={materials.mat15}
          />
        </group>
        <group
          name="FloatingIsland"
          position={[-0.226, -7.566, 0.948]}
          scale={4.404}
        >
          <mesh
            name="Leaves251"
            castShadow
            receiveShadow
            geometry={nodes.Leaves251.geometry}
            material={materials['Texture.001']}
            position={[-25.331, 59.056, -45.611]}
            rotation={[-Math.PI / 2, 0, -0.459]}
            scale={147.116}
          />
        </group>
        <group name="SignO" position={[-0.226, 25.707, 0.948]} scale={4.404}>
          <group name="Sign5" scale={100}>
            <mesh
              name="Sign5_1"
              castShadow
              receiveShadow
              geometry={nodes.Sign5_1.geometry}
              material={materials['Light Wood']}
            />
            <mesh
              name="Sign5_2"
              castShadow
              receiveShadow
              geometry={nodes.Sign5_2.geometry}
              material={materials['Dark Wood']}
            />
            <mesh
              name="Sign5_3"
              castShadow
              receiveShadow
              geometry={nodes.Sign5_3.geometry}
              material={materials.Herbs}
            />
          </group>
        </group>
        <mesh
          name="O"
          castShadow
          receiveShadow
          geometry={nodes.O.geometry}
          material={materials.O}
          position={[-92.733, 25.045, -51.426]}
          rotation={[-1.574, -0.002, 0.482]}
          scale={4.404}
        />
        <mesh
          name="X"
          castShadow
          receiveShadow
          geometry={nodes.X.geometry}
          material={materials.X}
          position={[109.598, 31.452, 22.129]}
          rotation={[0, -0.571, 0]}
          scale={4.404}
        />
        <mesh
          name="Text"
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials.O}
          position={[-41.231, 17.323, -26.583]}
          rotation={[1.57, 0, 0]}
          scale={4.404}
        />
        <mesh
          name="Cloud"
          castShadow
          receiveShadow
          geometry={nodes.Cloud.geometry}
          material={materials.lambert2SG}
          position={[298.334, 18.899, -111.516]}
          rotation={[0, -1.204, 0]}
          scale={4.404}
        />
        <mesh
          name="Cloud001"
          castShadow
          receiveShadow
          geometry={nodes.Cloud001.geometry}
          material={materials.lambert2SG}
          position={[323.852, 101.87, -160.467]}
          rotation={[0, -1.202, 0]}
          scale={4.404}
        />
        <mesh
          name="Cloud002"
          castShadow
          receiveShadow
          geometry={nodes.Cloud002.geometry}
          material={materials.lambert2SG}
          position={[237.987, 65.531, -197.313]}
          rotation={[0, -0.762, 0]}
          scale={4.404}
        />
        <mesh
          name="Cloud003"
          castShadow
          receiveShadow
          geometry={nodes.Cloud003.geometry}
          material={materials.lambert2SG}
          position={[152.739, 31.516, -219.649]}
          rotation={[0, -0.762, 0]}
          scale={4.404}
        />
        <mesh
          name="Cloud004"
          castShadow
          receiveShadow
          geometry={nodes.Cloud004.geometry}
          material={materials.lambert2SG}
          position={[131.225, 177.43, -317.453]}
          rotation={[0, -0.762, 0]}
          scale={4.404}
        />
        <mesh
          name="Cloud005"
          castShadow
          receiveShadow
          geometry={nodes.Cloud005.geometry}
          material={materials.lambert2SG}
          position={[-60.391, 55.73, -268.414]}
          scale={4.404}
        />
        <mesh
          name="Cloud006"
          castShadow
          receiveShadow
          geometry={nodes.Cloud006.geometry}
          material={materials.lambert2SG}
          position={[33.1, 81.593, -281.297]}
          scale={4.404}
        />
        <mesh
          name="Cloud007"
          castShadow
          receiveShadow
          geometry={nodes.Cloud007.geometry}
          material={materials.lambert2SG}
          position={[96.786, 123.029, -280.637]}
          scale={4.404}
        />
        <mesh
          name="Cloud008"
          castShadow
          receiveShadow
          geometry={nodes.Cloud008.geometry}
          material={materials.lambert2SG}
          position={[-33.287, 163.869, -273.878]}
          scale={4.404}
        />
        <mesh
          name="Cloud009"
          castShadow
          receiveShadow
          geometry={nodes.Cloud009.geometry}
          material={materials.lambert2SG}
          position={[-245.948, 143.179, -178.76]}
          rotation={[0, 0.77, 0]}
          scale={4.404}
        />
        <mesh
          name="Cloud010"
          castShadow
          receiveShadow
          geometry={nodes.Cloud010.geometry}
          material={materials.lambert2SG}
          position={[-261.749, 78.723, -144.715]}
          rotation={[0, 0.934, 0]}
          scale={4.404}
        />
        <mesh
          name="Cloud011"
          castShadow
          receiveShadow
          geometry={nodes.Cloud011.geometry}
          material={materials.lambert2SG}
          position={[-321.138, 109.065, -131.261]}
          rotation={[0, 0.934, 0]}
          scale={4.404}
        />
        <mesh
          name="Cloud012"
          castShadow
          receiveShadow
          geometry={nodes.Cloud012.geometry}
          material={materials.lambert2SG}
          position={[-285.253, 180.975, -160.374]}
          rotation={[0, 0.77, 0]}
          scale={4.404}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload('/Environment/Island.glb');
