/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';

export default function Wall(props) {
  const { nodes, materials } = useGLTF('/Environment/Wall.glb');
  return (
    <RigidBody type="fixed" colliders="hull" friction={5}>
      <group {...props} dispose={null}>
        <mesh
          name="Transparent"
          geometry={nodes.Transparent.geometry}
          material={materials['Transparent.001']}
          position={[0, 22.283, 1.656]}
        />
        <mesh
          name="Transparent001"
          geometry={nodes.Transparent001.geometry}
          material={materials['Transparent.001']}
          position={[0, 22.283, 35.852]}
        />
        <mesh
          name="Transparent002"
          geometry={nodes.Transparent002.geometry}
          material={materials['Transparent.001']}
          position={[35.497, 22.283, 42.54]}
          rotation={[0, 0.015, 0]}
        />
        <mesh
          name="Transparent003"
          geometry={nodes.Transparent003.geometry}
          material={materials['Transparent.001']}
          position={[63.485, 22.283, 47.452]}
          rotation={[0, 0.815, 0]}
        />
        <mesh
          name="Transparent004"
          geometry={nodes.Transparent004.geometry}
          material={materials['Transparent.001']}
          position={[88.421, 22.283, 34.991]}
          rotation={[-Math.PI, 1.501, -Math.PI]}
        />
        <mesh
          name="Transparent005"
          geometry={nodes.Transparent005.geometry}
          material={materials['Transparent.001']}
          position={[114.113, 22.283, 22.57]}
          rotation={[-Math.PI, 1.501, -Math.PI]}
        />
        <mesh
          name="Transparent006"
          geometry={nodes.Transparent006.geometry}
          material={materials['Transparent.001']}
          position={[118.963, 22.283, -8.657]}
          rotation={[-Math.PI, 0.878, -Math.PI]}
        />
        <mesh
          name="Transparent007"
          geometry={nodes.Transparent007.geometry}
          material={materials['Transparent.001']}
          position={[88.705, 22.283, -27.337]}
          rotation={[-Math.PI, 1.501, -Math.PI]}
        />
        <mesh
          name="Transparent008"
          geometry={nodes.Transparent008.geometry}
          material={materials['Transparent.001']}
          position={[63.304, 22.283, -18.541]}
          rotation={[-Math.PI, 1.501, -Math.PI]}
        />
        <mesh
          name="Transparent009"
          geometry={nodes.Transparent009.geometry}
          material={materials['Transparent.001']}
          position={[46.393, 22.283, -6.325]}
          rotation={[-Math.PI, 1.501, -Math.PI]}
        />
        <mesh
          name="Transparent010"
          geometry={nodes.Transparent010.geometry}
          material={materials['Transparent.001']}
          position={[-15.59, 22.283, 38.734]}
          rotation={[-Math.PI, 1.401, -Math.PI]}
        />
        <mesh
          name="Transparent011"
          geometry={nodes.Transparent011.geometry}
          material={materials['Transparent.001']}
          position={[-32.331, 22.283, 50.778]}
          rotation={[-Math.PI, 1.401, -Math.PI]}
        />
        <mesh
          name="Transparent012"
          geometry={nodes.Transparent012.geometry}
          material={materials['Transparent.001']}
          position={[-55.112, 22.283, 44.851]}
          rotation={[-Math.PI, 1.401, -Math.PI]}
        />
        <mesh
          name="Transparent013"
          geometry={nodes.Transparent013.geometry}
          material={materials['Transparent.001']}
          position={[-63.79, 22.283, 20.068]}
          rotation={[-Math.PI, 1.401, -Math.PI]}
        />
        <mesh
          name="Transparent014"
          geometry={nodes.Transparent014.geometry}
          material={materials['Transparent.001']}
          position={[-62.313, 22.283, -9.09]}
          rotation={[-Math.PI, 1.401, -Math.PI]}
        />
        <mesh
          name="Transparent015"
          geometry={nodes.Transparent015.geometry}
          material={materials['Transparent.001']}
          position={[-37.877, 22.283, -20.801]}
          rotation={[-Math.PI, 1.401, -Math.PI]}
        />
        <mesh
          name="Transparent016"
          geometry={nodes.Transparent016.geometry}
          material={materials['Transparent.001']}
          position={[-17.305, 22.283, -16.001]}
          rotation={[-Math.PI, 1.401, -Math.PI]}
        />
        <mesh
          name="Transparent017"
          geometry={nodes.Transparent017.geometry}
          material={materials['Transparent.001']}
          position={[-13.588, 22.283, -8.347]}
          rotation={[-Math.PI, 1.401, -Math.PI]}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload('/Environment/Wall.glb');
