/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function XBubble(props) {
  const { nodes, materials } = useGLTF('/Environment/XBubble.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Bubble"
        castShadow
        receiveShadow
        geometry={nodes.Bubble.geometry}
        material={materials.mat21}
        position={[-1.528, 1.662, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['X.001']}
        position={[0.398, 0.1, 1.068]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, -1, -0.204]}
      />
      <mesh
        name="Cube001"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['X.001']}
        position={[1.955, 2.683, 1.068]}
        rotation={[0, 0, -1.759]}
        scale={[-1, -1, -0.204]}
      />
    </group>
  );
}

useGLTF.preload('/Environment/XBubble.glb');
