/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function YesNo(props) {
  const { nodes, materials } = useGLTF('/Environment/YesNo.glb');
  return (
    <group {...props} dispose={null}>
      <group
        position={[-6.602, 13.594, 29.702]}
        rotation={[-Math.PI / 2, 0, 3.102]}
      >
        <mesh
          geometry={nodes.Arrow_Side004.geometry}
          material={materials['Wood.003']}
        />
        <mesh
          geometry={nodes.Arrow_Side004_1.geometry}
          material={materials.Main_Dark}
        />
        <mesh
          geometry={nodes.Arrow_Side004_2.geometry}
          material={materials.text}
        />
        <mesh
          geometry={nodes.Arrow_Side004_3.geometry}
          material={materials.Yes}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/Environment/YesNo.glb');
